### ISSUE TITLE
CJK characters not supported

### ISSUE THREAD

**Issue by linusboyle** [fiatjaf/neuron.vim#21]
![image](https://user-images.githubusercontent.com/33540801/94790307-a9cd8500-0408-11eb-9c7e-6ebc4f1e6f40.png)

All the wide characters are rendered as `?`.

`neuron` itself supports wide characters, so the problem should be related to this plugin.

**Comment by fiatjaf** [comment]
It's a problem of neuron, or something between neuron and your OS. I know because it happens on mine too with latin characters (and it shows up on `neuron query` output, for example, which is independent from this plugin and that this plugin uses). There was a change in the OS settings I did that fixed it, but I don't remember what was it and now my problem is back.

There was also an issue on the main neuron repo about this.
